api_version = "2025-07"

[[extensions]]
name = "My Wishlist"
handle = "wishlist-page"
uid = "bc7ed5a2-dae8-0291-b4b2-46fe268521762e1ba10a"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/index.tsx"
target = "customer-account.page.render"

[extensions.capabilities]
network_access = true
